<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hasil_transaksi extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hasil_transaksi_model');
        $this->load->model('Transaksi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $hasil_transaksi = $this->Hasil_transaksi_model->get_all_query();

        $data = array(
            'hasil_transaksi_data' => $hasil_transaksi
        );

        $this->template->load('template','hasil_transaksi/hasil_transaksi_list', $data);

       
    }

 
    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "hasil_transaksi.xls";
        $judul = "hasil_transaksi";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        
        xlsWriteLabel($tablehead, $kolomhead++, "No");
	    xlsWriteLabel($tablehead, $kolomhead++, "Nama Rekanan");
	    xlsWriteLabel($tablehead, $kolomhead++, "Total Debet");
        xlsWriteLabel($tablehead, $kolomhead++, "Total Kredit");
        xlsWriteLabel($tablehead, $kolomhead++, "Sisa Bayar");

	foreach ($this->Hasil_transaksi_model->get_all_query() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
        xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteLabel($tablebody, $kolombody++, $data->nama_rekanan);
	    xlsWriteNumber($tablebody, $kolombody++, $data->total_debet);
	    xlsWriteNumber($tablebody, $kolombody++, $data->total_kredit);
	    xlsWriteNumber($tablebody, $kolombody++, $data->sisa_bayar);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=hasil_transaksi.doc");

        $data = array(
            'hasil_transaksi_data' => $this->Hasil_transaksi_model->get_all_query(),
            'start' => 0
        );
        
        $this->load->view('hasil_transaksi_doc',$data);
    }

    public function detail_transaksi($id) 
    {
        $row = $this->Transaksi_model->get_by_id($id);
        if ($row) {
            $data = array(
        'id_transaksi' => $row->id_transaksi,
        'id_rekanan' => $row->id_rekanan,
        'tanggal' => $row->tanggal,
        'deskripsi' => $row->deskripsi,
        'retasi' => $row->retasi,
        'tonase' => $row->tonase,
        'kubikasi' => $row->kubikasi,
        'harga_dasar' => $row->harga_dasar,
        'debet' => $row->debet,
        'kredit' => $row->kredit,
        'keterangan' => $row->keterangan,
        );
            $this->template->load('template','hasil_transaksi/modal_tdetail', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('transaksi'));
        }
    }

}

/* End of file Hasil_transaksi.php */
/* Location: ./application/controllers/Hasil_transaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-22 12:21:54 */
/* http://harviacode.com */