<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hasil_transaksi_model extends CI_Model
{

    public $table = 'hasil_transaksi';
    public $id = 'id_h_transaksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_query()
    {
        $sql = " SELECT nama_rekanan, SUM(debet) as total_debet, SUM(kredit) as total_kredit, 
                 (SUM(kredit)-SUM(debet)) as sisa_bayar 
                 FROM transaksi 
                 LEFT JOIN rekanan USING(id_rekanan) 
                 GROUP BY id_rekanan";
                 
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_h_transaksi', $q);
	$this->db->or_like('id_rekanan', $q);
	$this->db->or_like('total_debet', $q);
	$this->db->or_like('total_kredit', $q);
	$this->db->or_like('sisa_bayar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_h_transaksi', $q);
	$this->db->or_like('id_rekanan', $q);
	$this->db->or_like('total_debet', $q);
	$this->db->or_like('total_kredit', $q);
	$this->db->or_like('sisa_bayar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Hasil_transaksi_model.php */
/* Location: ./application/models/Hasil_transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-22 12:21:54 */
/* http://harviacode.com */